name: Release MacOS

on:
  push:
    tags: [ '*' ]

jobs:
  build-and-publish-macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SFML
        run:  brew install sfml
      
      - name: Compile project
        run:  make

      # - name: Copy assets
      #   run:  make copyassets

      # - name: Clean directory
      #   run:  make clean
  
      # - name: Archive release
      #   uses: thedoctor0/zip-release@0.7.6
      #   with:
      #     type: 'zip'
      #     filename: 'macOS-arm64.zip'
      #     path: './bin/macOS-arm64'

      # - name: Publish binaries
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: macOS-arm64.zip
      #     asset_name: endless_dungeon-macOS-arm64-${{  github.ref_name }}.zip
      #     tag: ${{  github.ref_name }}
      #     overwrite: true